version: '3'

services:
  phoenix:
    build:
      context: .
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      POSTGRES_DATABASE: banking_api_dev
      POSTGRES_PORT: 5432
      DATABASE_URL: ecto://postgres:postgres@db/banking_api_dev
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 120
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
