version: '3'

services:
  web:
    build:
      context: .
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    command: mix phx.server
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: db
      MIX_ENV: dev
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - web:/opt/app
  db:
    image: postgres:9.6
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 120
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  test:
    image: banking_api_web
    command: mix test
    environment:
      MIX_ENV: test
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: db
    volumes:
      - web:/opt/app
    depends_on:
      - db
volumes:
  pgdata:
  web:
